import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../../../shared/infrastructure/prisma/prisma.service';
import { LoanType, LoanStatus, TransactionType } from '@prisma/client';

@Injectable()
export class GetDashboardSummaryUseCase {
    constructor(private readonly prisma: PrismaService) { }

    async execute(userId: string) {
        // 1. Real Balance: Sum of ALL transactions for this user.
        // This represents the actual money in accounts.
        const [totalIncomeAgg, totalExpenseAgg] = await Promise.all([
            this.prisma.transaction.aggregate({
                where: {
                    userId,
                    type: TransactionType.INCOME
                },
                _sum: { amount: true },
            }),
            this.prisma.transaction.aggregate({
                where: {
                    userId,
                    type: TransactionType.EXPENSE
                },
                _sum: { amount: true },
            })
        ]);

        const totalIncome = totalIncomeAgg._sum.amount?.toNumber() || 0;
        const totalExpense = totalExpenseAgg._sum.amount?.toNumber() || 0;
        const realBalance = totalIncome - totalExpense;

        // 2. Operational Balance: Income - Expenses (excluding loans)
        // This represents day-to-day spending power generated by earnings.
        const operationalIncomeAgg = await this.prisma.transaction.aggregate({
            where: {
                userId,
                type: TransactionType.INCOME,
                isLoan: false
            },
            _sum: { amount: true },
        });
        const operationalIncome = operationalIncomeAgg._sum.amount?.toNumber() || 0;

        const operationalExpenseAgg = await this.prisma.transaction.aggregate({
            where: {
                userId,
                type: TransactionType.EXPENSE,
                isLoan: false
            },
            _sum: { amount: true },
        });
        const operationalExpense = operationalExpenseAgg._sum.amount?.toNumber() || 0;
        const operationalBalance = operationalIncome - operationalExpense;

        // 3. Loans Summary
        // Debts (Loans RECEIVED that are ACTIVE)
        const debtsAgg = await this.prisma.loan.aggregate({
            where: {
                userId,
                type: LoanType.RECEIVED,
                status: LoanStatus.ACTIVE
            },
            _sum: { pendingAmount: true }
        });
        const totalDebts = debtsAgg._sum.pendingAmount?.toNumber() || 0;

        // Receivables (Loans GIVEN that are ACTIVE)
        const receivablesAgg = await this.prisma.loan.aggregate({
            where: {
                userId,
                type: LoanType.GIVEN,
                status: LoanStatus.ACTIVE
            },
            _sum: { pendingAmount: true }
        });
        const totalReceivables = receivablesAgg._sum.pendingAmount?.toNumber() || 0;

        return {
            realBalance,
            operationalBalance,
            operationalIncome,
            operationalExpense,
            totalDebts,
            totalReceivables,
        };
    }
}
